name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: autogen
      run: aclocal && autoheader && automake --foreign --add-missing --force-missing --copy && autoconf
    - name: Get libcurl-dev package
      uses: mstksg/get-package@v1
      with:
        apt-get: libcurl-dev
    - name: configure
      run: chmod +x ./configure && ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
